### PR TITLE
drop logic peers

### LINKED ISSUE #12: Drop peer list and discovery integration
All the logic that is related to peers should be either completely removed or extracted into another package.

### PR DESCRIPTION
**Pull request by Pedro-Souza**
fix #12

### CODE REVIEW

**Comment by Pedro-Souza** [comment]
I think we should create first for peers, and adapt the desktop wallet and upload a version here without the logic of peers

**Comment by j-a-m-l** [comment]
@Pedro-Souza you'll need to update the example to admit a new environment variable (something like `ARK_CLIENT_EXAMPLE_HOST`) or provide arguments to the script to specify the port.

**Comment by Pedro-Souza** [comment]
Do not just use ?
```
const client = new ArkEcosystemClient('<your host here>')
```

**Comment by j-a-m-l** [comment]
Ideally users wouldn't need to know beforehand, unless they want, which peer is online to connect to it. That was 1 of the utilities of the peer discovery feature, so, if 2 months from now, that peer doesn't exist, you wouldn't need to change your code.

@Pedro-Souza it would be easier to run the example using environment variables or arguments for the script (`send.js <port> <wallet> <pass>`) because the user wouldn't need to edit the file.

**Comment by faustbrian** [comment]
This behaviour will first need to be extracted into another module for JavaScript.

**Pull request closed without merging**
